src/Entity/Messages.php
<?php

namespace App\Entity;

use App\Repository\MessagesRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=MessagesRepository::class)
 */
class Messages
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     */
    private $message;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_read = 0;

    /**
     * @ORM\ManyToOne(targetEntity=Users::class, inversedBy="sent")
     * @ORM\JoinColumn(nullable=false)
     */
    private $sender;

    /**
     * @ORM\ManyToOne(targetEntity=Users::class, inversedBy="received")
     * @ORM\JoinColumn(nullable=false)
     */
    private $recipient;

    public function __construct()
    {
        $this->createdAt = new \DateTime();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getMessage(): ?string
    {
        return $this->message;
    }

    public function setMessage(string $message): self
    {
        $this->message = $message;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function isIsRead(): ?bool
    {
        return $this->is_read;
    }

    public function setIsRead(bool $is_read): self
    {
        $this->is_read = $is_read;

        return $this;
    }

    public function getSender(): ?Users
    {
        return $this->sender;
    }

    public function setSender(?Users $sender): self
    {
        $this->sender = $sender;

        return $this;
    }

    public function getRecipient(): ?Users
    {
        return $this->recipient;
    }

    public function setRecipient(?Users $recipient): self
    {
        $this->recipient = $recipient;

        return $this;
    }
}

src/Form/MessagesType.php
<?php

namespace App\Form;

use App\Entity\Users;
use App\Entity\Messages;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;

class MessagesType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title', TextType::class,[
                "attr" => [
                    "class" => "form-control"
                ]
            ])
            ->add('message', TextareaType::class,[
                "attr" => [
                    "class" => "form-control"
                ]
            ])
            ->add('recipient', EntityType::class,[
                "class" => Users::class,
                "choice_label" => "email",
                "attr" => [
                    "class" => "form-control"
                ]
            ])
            ->add('Envoyer', SubmitType::class, [
                "attr" => [
                    "class" => "btn btn-primary"
                ]
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Messages::class,
        ]);
    }
}

src/Controller/MessagesController.php
<?php

namespace App\Controller;

use App\Entity\Messages;
use App\Form\MessagesType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class MessagesController extends AbstractController
{
    /**
     * @Route("/messages", name="app_messages")
     */
    public function index(): Response
    {
        return $this->render('messages/index.html.twig', [
            'controller_name' => 'MessagesController',
        ]);
    }

    /**
     * @Route("/send", name="send")
     */
    public function send(Request $request): Response
    {
        $message = new Messages;
        $form = $this->createForm(MessagesType::class, $message);

        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid())
        {
            $message->setSender($this->getUser());

            $em = $this->getDoctrine()->getManager();
            $em->persist($message);
            $em->flush();

            $this->addFlash("message", "Message envoyé avec succès !");
            return $this->redirectToRoute("app_messages");
        }

        return $this->render("messages/send.html.twig", [
            "form" => $form->createView()
        ]);
    }

     /**
     * @Route("/received", name="received")
     */
    public function received(): Response
    {
        return $this->render('messages/received.html.twig');
    } 

     /**
     * @Route("/read/{id}", name="read")
     */
    public function read(Messages $message): Response
    {
        $message->setIsRead(true);
        $em = $this->getDoctrine()->getManager();
        $em->persist($message);
        $em->flush();

        return $this->render('messages/read.html.twig', compact("message"));
    } 

    /**
     * @Route("/delete/{id}", name="delete")
     */
    public function delete(Messages $message): Response
    {
        $em = $this->getDoctrine()->getManager();
        $em->remove($message);
        $em->flush();

        return $this->redirectToRoute("received");
    }

    /**
     * @Route("/sent", name="sent")
     */
    public function sent(): Response
    {
        return $this->render('messages/sent.html.twig');
    } 
}

templates/messages/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Messagerie Privée{% endblock %}

{% block body %}

    <section class="container">
        <div class="row">
            <div class="col">
                <h1>Messagerie</h1>
                <p>Résumé de la messagerie</p>
                <p>Reçus : {{ app.user.received|length }}</p>
                <p>Envoyés : {{ app.user.sent|length }}</p>
                <a class="btn btn-primary" data-bs-toggle="offcanvas" href="#offcanvasExample" role="button" aria-controls="offcanvasExample">
                Voir mes dossiers
                </a>
                <a href="{{ path('send') }}" class="btn btn-primary">Envoyer un message</a>

                <div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasExample" aria-labelledby="offcanvasExampleLabel">
                <div class="offcanvas-header">
                    <h2 class="offcanvas-title" id="offcanvasExampleLabel">Mes dossiers</h2>
                    <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
                </div>
                <div class="offcanvas-body">
                    <div class="list-group">
                        <a href="{{ path('app_messages') }}" class="list-group-item list-group-item-action active">Accueil</a>
                    </div>
                    <div class="list-group">
                        <a href="{{ path('received') }}" class="list-group-item list-group-item-action">Boite de réception</a>
                    </div>
                    <div class="list-group">
                        <a href="{{ path('sent') }}" class="list-group-item list-group-item-action">Eléments envoyés</a>
                    </div>

        </div>
    </div>

{% endblock %}

templates/messages/read.html.twig
{% extends 'base.html.twig' %}

{% block title %}Messagerie reçus{% endblock %}

{% block body %}

    <section class="container">
        <div class="row">
            <div class="col-12">
                <h1>Messagerie</h1>
                <h2>{{ message.title }}</h2>
                <p>Message de {{ message.sender.email }}</p>
                <p>Le {{ message.createdAt|date }}</p>
                <div>{{ message.message }}</div>


                <a class="btn btn-primary" data-bs-toggle="offcanvas" href="#offcanvasExample" role="button" aria-controls="offcanvasExample">
                Voir mes dossiers
                </a>
                <a href="{{ path('received') }}" class="btn btn-primary">Retour à la boite de réception</a>

                <div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasExample" aria-labelledby="offcanvasExampleLabel">
                <div class="offcanvas-header">
                    <h2 class="offcanvas-title" id="offcanvasExampleLabel">Mes dossiers</h2>
                    <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
                </div>
                <div class="offcanvas-body">
                    <div class="list-group">
                        <a href="{{ path('app_messages') }}" class="list-group-item list-group-item-action">Accueil</a>
                    </div>
                    <div class="list-group">
                        <a href="{{ path('received') }}" class="list-group-item list-group-item-action active">Boite de réception</a>
                    </div>
                    <div class="list-group">
                        <a href="{{ path('sent') }}" class="list-group-item list-group-item-action">Eléments envoyés</a>
                    </div>

        </div>
    </div>

{% endblock %}

templates/messages/received.html.twig
{% extends 'base.html.twig' %}

{% block title %}Messagerie reçus{% endblock %}

{% block body %}

    <section class="container">
        <div class="row">
            <div class="col-12">
                <h1>Messagerie</h1>
                <h2>Boite de réception</h2>
                <p>Vous avez reçu : {{ app.user.received|length }} messages</p>
                </div>
                <div class="col-3">De</div>
                <div class="col-3">Sujet</div>
                <div class="col-3">Date</div>
                <div class="col-3">Actions</div>

                {% for message in app.user.received %}

                    {% if message.isRead == 0 %}
                        {% set bold = "fw-bold" %}
                    {% else %}
                        {% set bold = "" %}
                    {% endif %}
                    
                <div class="col-3 {{ bold }}">{{ message.sender.email }}</div>
                <div class="col-3 {{ bold }}"><a href="{{ path('read', {id:message.id}) }}">{{ message.title }}</a></div>
                <div class="col-3 {{ bold }}">{{ message.createdAt|date }}</div>
                <div class="col-3"><a href="{{ path("delete", {id:message.id}) }}">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-x-square-fill text-danger" viewBox="0 0 16 16">
                    <path d="M2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2zm3.354 4.646L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 1 1 .708-.708z"/>
                    </svg></a>
                </div>

                {% endfor %}

                <div class="col">
                <a class="btn btn-primary" data-bs-toggle="offcanvas" href="#offcanvasExample" role="button" aria-controls="offcanvasExample">
                Voir mes dossiers
                </a>
                <a href="{{ path('send') }}" class="btn btn-primary">Envoyer un message</a>

                <div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasExample" aria-labelledby="offcanvasExampleLabel">
                <div class="offcanvas-header">
                    <h2 class="offcanvas-title" id="offcanvasExampleLabel">Mes dossiers</h2>
                    <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
                </div>
                <div class="offcanvas-body">
                    <div class="list-group">
                        <a href="{{ path('app_messages') }}" class="list-group-item list-group-item-action">Accueil</a>
                    </div>
                    <div class="list-group">
                        <a href="{{ path('received') }}" class="list-group-item list-group-item-action active">Boite de réception</a>
                    </div>
                    <div class="list-group">
                        <a href="{{ path('sent') }}" class="list-group-item list-group-item-action">Eléments envoyés</a>
                    </div>

        </div>
    </div>

{% endblock %}

templates/messages/send.html.twig
{% extends 'base.html.twig' %}

{% block title %}Messagerie Privée{% endblock %}

{% block body %}

    <section class="container">
        <div class="row">
            <div class="col">
                <h1>Envoyer un message</h1>
                    {{ form(form)}}
                <a class="btn btn-primary" data-bs-toggle="offcanvas" href="#offcanvasExample" role="button" aria-controls="offcanvasExample">
                Voir mes dossiers
                </a>
                <div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasExample" aria-labelledby="offcanvasExampleLabel">
                <div class="offcanvas-header">
                    <h2 class="offcanvas-title" id="offcanvasExampleLabel">Mes dossiers</h2>
                    <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
                </div>
                <div class="offcanvas-body">
                    <div class="list-group">
                        <a href="{{ path('app_messages') }}" class="list-group-item list-group-item-action">Accueil</a>
                    </div>
                    <div class="list-group">
                        <a href="{{ path('received') }}" class="list-group-item list-group-item-action">Boite de réception</a>
                    </div>
                    <div class="list-group">
                        <a href="{{ path('sent') }}" class="list-group-item list-group-item-action">Eléments envoyés</a>
                    </div>

        </div>
    </div>

{% endblock %}

templates/messages/sent.html.twig
{% extends 'base.html.twig' %}

{% block title %}Messagerie reçus{% endblock %}

{% block body %}

    <section class="container">
        <div class="row">
            <div class="col-12">
                <h1>Messagerie</h1>
                <h2>Eléments envoyés</h2>
                <p>Vous avez envoyé : {{ app.user.received|length }} messages</p>
                </div>
                <div class="col-3">De</div>
                <div class="col-3">Sujet</div>
                <div class="col-3">Date</div>
                <div class="col-3">Actions</div>

                {% for message in app.user.sent %}

                    {% if message.isRead == 0 %}
                        {% set bold = "fw-bold" %}
                    {% else %}
                        {% set bold = "" %}
                    {% endif %}
                    
                <div class="col-3 {{ bold }}">{{ message.sender.email }}</div>
                <div class="col-3 {{ bold }}"><a href="{{ path('read', {id:message.id}) }}">{{ message.title }}</a></div>
                <div class="col-3 {{ bold }}">{{ message.createdAt|date }}</div>
                <div class="col-3"><a href="{{ path("delete", {id:message.id}) }}">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-x-square-fill text-danger" viewBox="0 0 16 16">
                    <path d="M2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2zm3.354 4.646L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 1 1 .708-.708z"/>
                    </svg></a>
                </div>

                {% endfor %}

                <div class="col">
                <a class="btn btn-primary" data-bs-toggle="offcanvas" href="#offcanvasExample" role="button" aria-controls="offcanvasExample">
                Voir mes dossiers
                </a>
                <a href="{{ path('send') }}" class="btn btn-primary">Envoyer un message</a>

                <div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasExample" aria-labelledby="offcanvasExampleLabel">
                <div class="offcanvas-header">
                    <h2 class="offcanvas-title" id="offcanvasExampleLabel">Mes dossiers</h2>
                    <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
                </div>
                <div class="offcanvas-body">
                    <div class="list-group">
                        <a href="{{ path('app_messages') }}" class="list-group-item list-group-item-action">Accueil</a>
                    </div>
                    <div class="list-group">
                        <a href="{{ path('received') }}" class="list-group-item list-group-item-action">Boite de réception</a>
                    </div>
                    <div class="list-group">
                        <a href="{{ path('sent') }}" class="list-group-item list-group-item-action active">Eléments envoyés</a>
                    </div>
        </div>
    </div>

{% endblock %}